/**
 * GramVerse AI - Nationwide Village Registry & Data Source Tier Classification
 * Designed for multi-source GIS expansion across Indian States and Panchayats (SIH1704).
 */

export const DATA_TIERS = {
  TIER_1: {
    id: 'tier1_drone_gis',
    label: 'Drone Survey + GIS Cadastral',
    shortLabel: 'Drone + GIS',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
    dotColor: 'bg-emerald-400',
    description: 'High-resolution drone orthomosaic (5cm/px) paired with cadastral land parcel GIS data. Full simulation & shortest-path Dijkstra engine active.',
    isLiveSimSupported: true,
  },
  TIER_2: {
    id: 'tier2_satellite_gis_dem',
    label: 'Satellite GIS + SRTM DEM Elevation',
    shortLabel: 'GIS + DEM',
    badgeColor: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40',
    dotColor: 'bg-cyan-400',
    description: 'OpenStreetMap road network + 30m SRTM digital elevation model + village boundary. Standard regional planning resolution.',
    isLiveSimSupported: false,
    notice: 'Drone survey scheduled under SVAMITVA phase 2. Basic GIS layer view active.',
  },
  TIER_3: {
    id: 'tier3_census_boundary',
    label: 'Census Boundary Only (Survey Pending)',
    shortLabel: 'Census Only',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
    dotColor: 'bg-amber-400',
    description: 'Administrative boundary and census demographic attributes only. Drone cadastral survey pending.',
    isLiveSimSupported: false,
    notice: 'High-resolution cadastral data pending drone survey acquisition.',
  },
};

export const VILLAGE_REGISTRY = [
  {
    id: 'PB-PAT-001',
    name: 'Kalyan (Pilot Village)',
    subDistrict: 'Patiala Rural',
    district: 'Patiala',
    state: 'Punjab',
    pincode: '147001',
    center: [30.3695, 76.3775],
    zoom: 16,
    dataTier: DATA_TIERS.TIER_1,
    surveyDate: 'October 2024',
    surveyAgency: 'Survey of India / Drone Flight Unit 4',
    flightAltitude: '120m AGL',
    spatialResolution: '4.8 cm/pixel',
    terrainClass: 'Alluvial Plain (Slope < 2%)',
    areaHectares: 142.5,
    householdsCount: 10,
    population: 680,
    activeBackendId: 'patiala_pilot',
  },
  {
    id: 'PB-SAS-002',
    name: 'Gharuan (Smart Hub)',
    subDistrict: 'Kharar',
    district: 'SAS Nagar (Mohali)',
    state: 'Punjab',
    pincode: '140413',
    center: [30.7046, 76.5754],
    zoom: 16,
    dataTier: DATA_TIERS.TIER_1,
    isPilot: true,
    surveyDate: 'March 2025 (Drone Cadastral Survey)',
    surveyAgency: 'Survey of India / SVAMITVA Unit 7',
    flightAltitude: '100m AGL',
    spatialResolution: '4.2 cm/pixel',
    terrainClass: 'Smart Rural Alluvial Plain',
    areaHectares: 215.0,
    householdsCount: 12,
    population: 1450,
    activeBackendId: 'PB-SAS-002',
  },
  {
    id: 'MH-PUN-003',
    name: 'Ralegan Siddhi',
    subDistrict: 'Parner',
    district: 'Ahmednagar / Pune Zone',
    state: 'Maharashtra',
    pincode: '414302',
    center: [18.9189, 74.4078],
    zoom: 15,
    dataTier: DATA_TIERS.TIER_2,
    surveyDate: 'January 2024',
    surveyAgency: 'MRSAC / OSM GIS',
    flightAltitude: 'N/A (Satellite)',
    spatialResolution: '12.5 m (ALOS PALSAR DEM)',
    terrainClass: 'Watershed & Undulating Plateau',
    areaHectares: 980.0,
    householdsCount: 380,
    population: 2100,
  },
  {
    id: 'UP-VAR-004',
    name: 'Jayapur',
    subDistrict: 'Araziline',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    pincode: '221305',
    center: [25.2677, 82.8872],
    zoom: 15,
    dataTier: DATA_TIERS.TIER_3,
    surveyDate: 'Census 2021 Update',
    surveyAgency: 'Panchayati Raj Dept UP',
    flightAltitude: 'Pending Drone Flight',
    spatialResolution: 'Administrative Vector',
    terrainClass: 'Gangetic Alluvial Plain',
    areaHectares: 310.0,
    householdsCount: 650,
    population: 4120,
  },
  {
    id: 'KA-MYS-005',
    name: 'Talakadu',
    subDistrict: 'T. Narasipura',
    district: 'Mysuru',
    state: 'Karnataka',
    pincode: '571122',
    center: [12.1932, 77.0321],
    zoom: 15,
    dataTier: DATA_TIERS.TIER_2,
    surveyDate: 'August 2024',
    surveyAgency: 'KSRSAC / CartoDEM',
    flightAltitude: 'N/A (Satellite)',
    spatialResolution: '10 m/pixel',
    terrainClass: 'Riverine Basin (Cauvery Delta)',
    areaHectares: 450.0,
    householdsCount: 510,
    population: 2980,
  },
  {
    id: 'RJ-JAI-006',
    name: 'Piplantri',
    subDistrict: 'Rajsamand',
    district: 'Rajsamand / Jaipur Zone',
    state: 'Rajasthan',
    pincode: '313324',
    center: [25.0712, 73.8821],
    zoom: 15,
    dataTier: DATA_TIERS.TIER_3,
    surveyDate: 'Census 2021 Update',
    surveyAgency: 'DoIT&C Rajasthan',
    flightAltitude: 'Scheduled Q3 2025',
    spatialResolution: 'Administrative Vector',
    terrainClass: 'Aravalli Semi-Arid Hilly',
    areaHectares: 620.0,
    householdsCount: 440,
    population: 2650,
  },
];
